"""add table rooms

Revision ID: 4f0c1a288111
Revises: 7fb8dd4a6107
Create Date: 2026-05-15 15:47:19.493143

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "4f0c1a288111"
down_revision: Union[str, Sequence[str], None] = "7fb8dd4a6107"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rooms")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rooms",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("hotel_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("title", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("price", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("quantity", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["hotel_id"], ["hotels.id"], name=op.f("rooms_hotel_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("rooms_pkey")),
    )
    # ### end Alembic commands ###
