"""add bookingasdsads

Revision ID: f4157e8013c2
Revises: 63b47c0c67dd
Create Date: 2026-05-25 00:18:27.214087

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "f4157e8013c2"
down_revision: Union[str, Sequence[str], None] = "63b47c0c67dd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bookings", sa.Column("date_form", sa.Date(), nullable=False))
    op.drop_column("bookings", "date_format")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bookings",
        sa.Column("date_format", sa.DATE(), autoincrement=False, nullable=False),
    )
    op.drop_column("bookings", "date_form")
    # ### end Alembic commands ###
